// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/:id": {
    params: {
      "id": string;
    };
  };
  "/hevy": {
    params: {};
  };
  "/hevy/mapping/:templateId": {
    params: {
      "templateId": string;
    };
  };
  "/hevy/mappings": {
    params: {};
  };
  "/hevy/mappings/mapping/:templateId": {
    params: {
      "templateId": string;
    };
  };
  "/settings": {
    params: {};
  };
  "/setup": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/:id" | "/hevy" | "/hevy/mapping/:templateId" | "/hevy/mappings" | "/hevy/mappings/mapping/:templateId" | "/settings" | "/setup";
  };
  "./routes/app-layout.tsx": {
    id: "routes/app-layout";
    page: "/" | "/:id" | "/hevy" | "/hevy/mapping/:templateId" | "/hevy/mappings" | "/hevy/mappings/mapping/:templateId" | "/settings";
  };
  "./routes/activities.tsx": {
    id: "routes/activities";
    page: "/" | "/:id";
  };
  "./routes/activity-detail.tsx": {
    id: "routes/activity-detail";
    page: "/:id";
  };
  "./routes/hevy.tsx": {
    id: "routes/hevy";
    page: "/hevy" | "/hevy/mapping/:templateId";
  };
  "./routes/hevy-mapping.tsx": {
    id: "routes/hevy-mapping";
    page: "/hevy/mapping/:templateId";
  } | {
    id: "mappings-mapping";
    page: "/hevy/mappings/mapping/:templateId";
  };
  "./routes/hevy-mappings.tsx": {
    id: "routes/hevy-mappings";
    page: "/hevy/mappings" | "/hevy/mappings/mapping/:templateId";
  };
  "./routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "./routes/setup.tsx": {
    id: "routes/setup";
    page: "/setup";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/app-layout": typeof import("./app/./routes/app-layout.tsx");
  "routes/activities": typeof import("./app/./routes/activities.tsx");
  "routes/activity-detail": typeof import("./app/./routes/activity-detail.tsx");
  "routes/hevy": typeof import("./app/./routes/hevy.tsx");
  "routes/hevy-mapping": typeof import("./app/./routes/hevy-mapping.tsx");
  "routes/hevy-mappings": typeof import("./app/./routes/hevy-mappings.tsx");
  "mappings-mapping": typeof import("./app/./routes/hevy-mapping.tsx");
  "routes/settings": typeof import("./app/./routes/settings.tsx");
  "routes/setup": typeof import("./app/./routes/setup.tsx");
};