"""Hevy ``exercise_template_id`` -> Garmin ``(category, subcategory)``.

Copied verbatim from hevy2garmin (MIT, github.com/secunit404/hevy2garmin),
where it is auto-generated by ``scripts/gen_template_map.py``. Language-
independent: the template id is the same regardless of the user's Hevy
language. Do not edit by hand; regenerate upstream and re-copy.
"""

from __future__ import annotations

TEMPLATE_TO_GARMIN: dict[str, tuple[int, int]] = {
    "3BC06AD3": (7, 3),  # 21s Bicep Curl
    "B4F2FF72": (5, 49),  # Ab Scissors
    "99D5F10E": (5, 18),  # Ab Wheel
    "5E0DDACE": (2, 0),  # Aerobics
    "43573BB8": (41, 0),  # Air Bike
    "A69FF221": (24, 1),  # Arnold Press (Dumbbell)
    "D4A2FE7E": (14, 32),  # Around The World
    "5BFF35BA": (28, 47),  # Assisted Pistol Squats
    "4F5866F8": (13, 25),  # Back Extension (Hyperextension)
    "A05C064D": (13, 25),  # Back Extension (Machine)
    "091737FA": (13, 26),  # Back Extension (Weighted Hyperextension)
    "F51D9080": (20, 25),  # Ball Slams
    "E8D86EE8": (9, 5),  # Band Pullaparts
    "084A67CA": (38, 0),  # Battle Ropes
    "DDB29047": (7, 4),  # Behind the Back Bicep Wrist Curl (Barbell)
    "2DBCA395": (7, 7),  # Behind the Back Curl (Cable)
    "3D1CDC75": (28, 61),  # Belt Squat (Machine)
    "CD6DC8E5": (30, 0),  # Bench Dip
    "79D0BB3A": (0, 1),  # Bench Press (Barbell)
    "99C1F2AD": (0, 20),  # Bench Press (Cable)
    "3601968B": (0, 6),  # Bench Press (Dumbbell)
    "0FBF7195": (0, 22),  # Bench Press (Smith Machine)
    "35B51B87": (0, 4),  # Bench Press - Close Grip (Barbell)
    "E644F828": (0, 25),  # Bench Press - Wide Grip (Barbell)
    "EA820646": (23, 0),  # Bent Over Row (Band)
    "55E6546F": (23, 46),  # Bent Over Row (Barbell)
    "23E92538": (23, 2),  # Bent Over Row (Dumbbell)
    "A5AC6449": (7, 3),  # Bicep Curl (Barbell)
    "ADA8623C": (7, 8),  # Bicep Curl (Cable)
    "37FCC2BB": (7, 37),  # Bicep Curl (Dumbbell)
    "AF328E3D": (7, 8),  # Bicep Curl (Machine)
    "0B4C1902": (7, 37),  # Bicep Curl (Suspension)
    "A41C7261": (6, 0),  # Bicycle Crunch
    "594450D2": (6, 0),  # Bicycle Crunch Raised Legs
    "BD0AD077": (11, 1),  # Bird Dog
    "56092DD1": (20, 13),  # Box Jump
    "38FC1AB9": (28, 7),  # Box Squat (Barbell)
    "A0D8FA1B": (2, 42),  # Boxing
    "B5D3A742": (17, 7),  # Bulgarian Split Squat
    "BB792A36": (29, 0),  # Burpee
    "86B00DDE": (29, 0),  # Burpee Over the Bar
    "9DCE2D64": (9, 2),  # Butterfly (Pec Deck)
    "23A48484": (6, 1),  # Cable Crunch
    "651F844C": (9, 0),  # Cable Fly Crossovers
    "8C331CD8": (10, 11),  # Cable Pull Through
    "92D858EA": (4, 2),  # Cable Twist (Down to up)
    "A2D838BD": (4, 2),  # Cable Twist (Up to down)
    "47B9DF13": (1, 18),  # Calf Extension (Machine)
    "91237BDD": (1, 18),  # Calf Press (Machine)
    "6FCD7755": (30, 2),  # Chest Dip
    "E9E4089F": (30, 2),  # Chest Dip (Assisted)
    "29472BE1": (30, 40),  # Chest Dip (Weighted)
    "DDB7C19F": (9, 2),  # Chest Fly (Band)
    "12017185": (9, 2),  # Chest Fly (Dumbbell)
    "78683336": (9, 2),  # Chest Fly (Machine)
    "720B0D70": (9, 2),  # Chest Fly (Suspension)
    "EAC7D9C5": (0, 1),  # Chest Press (Band)
    "7EB3F7C3": (0, 6),  # Chest Press (Machine)
    "914F3A96": (23, 40),  # Chest Supported Incline Row (Dumbbell)
    "B582299E": (9, 5),  # Chest Supported Reverse Fly (Dumbbell)
    "F21D5693": (14, 10),  # Chest Supported Y Raise (Dumbbell)
    "29083183": (21, 3),  # Chin Up
    "D23C609B": (21, 3),  # Chin Up (Assisted)
    "023943F1": (21, 4),  # Chin Up (Weighted)
    "CC016611": (10, 44),  # Clamshell
    "10D76E8F": (22, 7),  # Clap Push Ups
    "ABB00838": (18, 11),  # Clean
    "9E09CEC3": (18, 5),  # Clean and Jerk
    "D3095577": (18, 5),  # Clean and Press
    "652FEA39": (18, 11),  # Clean Pull
    "E23F1F2B": (2, 0),  # Climbing
    "724CDE60": (7, 37),  # Concentration Curl
    "32C4D4A2": (7, 12),  # Cross Body Hammer Curl
    "DCF3B31B": (6, 83),  # Crunch
    "EB43ADD4": (6, 28),  # Crunch (Machine)
    "D928C232": (6, 79),  # Crunch (Weighted)
    "D39EC9EB": (17, 21),  # Curtsy Lunge (Dumbbell)
    "D8F7F851": (33, 0),  # Cycling
    "D8911FC4": (11, 1),  # Dead Bug
    "B9380898": (21, 38),  # Dead Hang
    "99507114": (8, 0),  # Deadlift (Band)
    "C6272009": (8, 0),  # Deadlift (Barbell)
    "5F4E6DD3": (8, 2),  # Deadlift (Dumbbell)
    "20870ED5": (8, 0),  # Deadlift (Smith Machine)
    "B923B230": (8, 17),  # Deadlift (Trap bar)
    "FA5D0DE1": (8, 16),  # Deadlift High Pull
    "DA0F0470": (0, 5),  # Decline Bench Press (Barbell)
    "18487FA7": (0, 5),  # Decline Bench Press (Dumbbell)
    "FAF31231": (0, 5),  # Decline Bench Press (Machine)
    "FFC106CB": (0, 22),  # Decline Bench Press (Smith Machine)
    "A351AED7": (9, 1),  # Decline Chest Fly (Dumbbell)
    "BC10A922": (6, 83),  # Decline Crunch
    "B2398CD1": (6, 79),  # Decline Crunch (Weighted)
    "C43825EA": (22, 13),  # Decline Push Up
    "6575F52D": (22, 15),  # Diamond Push Up
    "7DA843A3": (31, 0),  # Downward Dog
    "D950429E": (7, 3),  # Drag Curl
    "AFC29472": (16, 1),  # Dragon Flag
    "B7192800": (16, 1),  # Dragonfly
    "F1E57334": (23, 2),  # Dumbbell Row
    "F3717B0E": (18, 16),  # Dumbbell Snatch
    "F72FA239": (0, 6),  # Dumbbell Squeeze Press
    "BF6ECE89": (28, 32),  # Dumbbell Step Up
    "A01BE509": (27, 37),  # Elbow to Knee
    "3303376C": (39, 0),  # Elliptical Trainer
    "01A35BF9": (7, 19),  # EZ Bar Biceps Curl
    "BE640BA0": (23, 5),  # Face Pull
    "50C613D0": (3, 1),  # Farmers Walk
    "867AC3B6": (0, 1),  # Feet Up Bench Press (Barbell)
    "2AF8B552": (11, 5),  # Fire Hydrants
    "D53F2886": (0, 3),  # Floor Press (Barbell)
    "756EE329": (0, 7),  # Floor Press (Dumbbell)
    "A57D38D5": (30, 0),  # Floor Triceps Dip
    "2FA77B28": (6, 13),  # Flutter Kicks
    "207DC636": (20, 3),  # Frog Jumps
    "F6948F17": (10, 11),  # Frog Pumps (Dumbbell)
    "0E608350": (21, 38),  # Front Lever Hold
    "30F03BF0": (21, 38),  # Front Lever Raise
    "47B036EF": (14, 10),  # Front Raise (Band)
    "BD86EFD5": (14, 10),  # Front Raise (Barbell)
    "DBB91A3C": (14, 5),  # Front Raise (Cable)
    "8293E554": (14, 10),  # Front Raise (Dumbbell)
    "796E8E2C": (14, 10),  # Front Raise (Suspension)
    "5046D0A9": (28, 8),  # Front Squat
    "1283BBA6": (28, 6),  # Full Squat
    "CDA23948": (10, 11),  # Glute Bridge
    "68B83EE0": (10, 11),  # Glute Ham Raise
    "CBA02382": (11, 17),  # Glute Kickback (Machine)
    "987234AB": (11, 17),  # Glute Kickback on Floor
    "3D0C7C75": (28, 37),  # Goblet Squat
    "4180C405": (15, 2),  # Good Morning (Barbell)
    "05487216": (23, 9),  # Gorilla Row (Kettlebell)
    "AC5A4C58": (28, 9),  # Hack Squat
    "1E42FD5F": (28, 9),  # Hack Squat (Machine)
    "1D4B3D6B": (7, 16),  # Hammer Curl (Band)
    "36E8F14E": (7, 9),  # Hammer Curl (Cable)
    "7E3BC8B6": (7, 16),  # Hammer Curl (Dumbbell)
    "BE3615CF": (22, 25),  # Handstand Hold
    "90B04F96": (22, 25),  # Handstand Push Up
    "BD4E7E53": (18, 0),  # Hang Clean
    "F4E77594": (18, 6),  # Hang Snatch
    "08590920": (16, 0),  # Hanging Knee Raise
    "F8356514": (16, 1),  # Hanging Leg Raise
    "567FB505": (6, 83),  # Heel Taps
    "BE89C631": (0, 6),  # Hex Press (Dumbbell)
    "C9CCB878": (20, 3),  # High Knee Skips
    "150E076B": (2, 0),  # High Knees
    "023947AB": (2, 0),  # HIIT
    "1C34A172": (32, 1),  # Hiking
    "F4B4C6EE": (11, 28),  # Hip Abduction (Machine)
    "8BEBFED6": (11, 25),  # Hip Adduction (Machine)
    "92B8C7E1": (10, 0),  # Hip Thrust
    "D57C2EC7": (10, 1),  # Hip Thrust (Barbell)
    "68CE0B9B": (10, 1),  # Hip Thrust (Machine)
    "291ABA92": (10, 1),  # Hip Thrust (Smith Machine)
    "970ADF87": (6, 24),  # Hollow Rock
    "50DFDFAB": (0, 8),  # Incline Bench Press (Barbell)
    "07B38369": (0, 9),  # Incline Bench Press (Dumbbell)
    "3A6FA3D1": (0, 8),  # Incline Bench Press (Smith Machine)
    "D3E2AB55": (9, 3),  # Incline Chest Fly (Dumbbell)
    "FBF92739": (0, 9),  # Incline Chest Press (Machine)
    "39C99849": (22, 27),  # Incline Push Ups
    "425805F4": (23, 10),  # Inverted Row
    "24706DCD": (0, 6),  # Iso-Lateral Chest Press (Machine)
    "BC3492DA": (23, 18),  # Iso-Lateral High Row (Machine)
    "91FAFBA3": (23, 18),  # Iso-Lateral Low Row
    "AA1EB7D8": (23, 2),  # Iso-Lateral Row (Machine)
    "D410F649": (6, 83),  # Jack Knife (Suspension)
    "32B0B590": (27, 37),  # Jackknife Sit Up
    "74103F24": (0, 4),  # JM Press (Barbell)
    "040BA2E3": (2, 6),  # Jump Rope
    "BA3DE542": (26, 0),  # Jump Shrug
    "70D4EBBF": (20, 3),  # Jump Squat
    "991833C2": (2, 12),  # Jumping Jack
    "5CC07A1F": (20, 0),  # Jumping Lunge
    "55BA475A": (5, 46),  # Kettlebell Around the World
    "F99C211D": (18, 11),  # Kettlebell Clean
    "4E239ED8": (7, 24),  # Kettlebell Curl
    "A127DA73": (28, 37),  # Kettlebell Goblet Squat
    "4288G454": (25, 3),  # Kettlebell Halo
    "9B13BA4B": (18, 8),  # Kettlebell High Pull
    "6433CD93": (24, 15),  # Kettlebell Shoulder Press
    "89304423": (18, 18),  # Kettlebell Snatch
    "F8A0FCCA": (10, 23),  # Kettlebell Swing
    "5F8903BF": (29, 0),  # Kettlebell Turkish Get Up
    "A91838C0": (21, 32),  # Kipping Pull Up
    "98237BA2": (16, 0),  # Knee Raise Parallel Bars
    "D82EA543": (21, 11),  # Kneeling Pulldown (band)
    "B74A95BB": (22, 33),  # Kneeling Push Up
    "6D54A050": (16, 1),  # L-Sit Hold
    "923874CA": (4, 2),  # Landmine 180
    "D7D7FCCE": (23, 13),  # Landmine Row
    "983274DD": (28, 79),  # Landmine Squat and Press
    "D2FE7B2E": (21, 13),  # Lat Pulldown (Band)
    "6A6C31A5": (21, 13),  # Lat Pulldown (Cable)
    "473CF5B8": (21, 13),  # Lat Pulldown (Machine)
    "4E5257DE": (21, 5),  # Lat Pulldown - Close Grip (Cable)
    "EC02979E": (11, 11),  # Lateral Band Walks
    "07EBC4DC": (20, 19),  # Lateral Box Jump
    "DC59D143": (11, 21),  # Lateral Leg Raises
    "F2A37357": (17, 32),  # Lateral Lunge
    "DF200976": (14, 11),  # Lateral Raise (Band)
    "BE289E45": (14, 14),  # Lateral Raise (Cable)
    "422B08F1": (14, 11),  # Lateral Raise (Dumbbell)
    "D5D0354D": (14, 24),  # Lateral Raise (Machine)
    "D731CCA8": (28, 61),  # Lateral Squat
    "75A4F6C4": (6, 33),  # Leg Extension (Machine)
    "C7973E0E": (28, 0),  # Leg Press (Machine)
    "0EB695C9": (28, 0),  # Leg Press Horizontal (Machine)
    "0482DA98": (16, 1),  # Leg Raise Parallel Bars
    "293483AD": (9, 0),  # Low Cable Fly Crossovers
    "8A2E6481": (23, 26),  # Low Row (Suspension)
    "5E1A7777": (17, 32),  # Lunge
    "6E6EE645": (17, 10),  # Lunge (Barbell)
    "B537D09F": (17, 21),  # Lunge (Dumbbell)
    "BD5935CF": (16, 8),  # Lying Knee Raise
    "B8127AD1": (15, 0),  # Lying Leg Curl (Machine)
    "09C9F635": (16, 8),  # Lying Leg Raise
    "22FEDCA4": (65534, 0),  # Lying Neck Curls
    "31B8DA0F": (65534, 0),  # Lying Neck Curls (Weighted)
    "0910BD28": (65534, 0),  # Lying Neck Extension
    "D6A73CF2": (65534, 0),  # Lying Neck Extension (Weighted)
    "C732C341": (23, 13),  # Meadows Rows (Barbell)
    "F49E31D6": (19, 34),  # Mountain Climber
    "9F9C164B": (14, 13),  # Muscle Up
    "F60BDDF8": (21, 38),  # Negative Pull Up
    "108D7A14": (15, 0),  # Nordic Hamstrings Curls
    "DBE341AA": (6, 83),  # Oblique Crunch
    "B140095E": (22, 38),  # One Arm Push Up
    "582ADA23": (7, 8),  # Overhead Curl (Cable)
    "4C6721B9": (3, 4),  # Overhead Dumbbell Lunge
    "54E60954": (14, 16),  # Overhead Plate Raise
    "7B8D84E8": (24, 14),  # Overhead Press (Barbell)
    "6AC96645": (24, 15),  # Overhead Press (Dumbbell)
    "B09A1304": (24, 20),  # Overhead Press (Smith Machine)
    "2CFED196": (28, 44),  # Overhead Squat
    "B5EFBF9C": (30, 5),  # Overhead Triceps Extension (Cable)
    "FBEE8279": (10, 0),  # Partial Glute Bridge (Barbell)
    "CE1054CE": (28, 6),  # Pause Squat (Barbell)
    "018ADC12": (23, 46),  # Pendlay Row (Barbell)
    "30E293E3": (28, 61),  # Pendulum Squat (Machine)
    "0EFE8162": (22, 49),  # Pike Pushup
    "EC2510CD": (2, 0),  # Pilates
    "942BAD12": (7, 12),  # Pinwheel Curl (Dumbbell)
    "3FF6A22E": (28, 47),  # Pistol Squat
    "C6C9B8A0": (19, 43),  # Plank
    "31436F5D": (22, 77),  # Plank Pushup
    "9283ABD5": (7, 27),  # Plate Curl
    "DBF9273A": (14, 16),  # Plate Front Raise
    "982734D4": (0, 12),  # Plate Press
    "9373FSD1": (0, 12),  # Plate Squeeze (Svend Press)
    "C628D768": (18, 2),  # Power Clean
    "E22F9358": (18, 3),  # Power Snatch
    "4F942934": (7, 19),  # Preacher Curl (Barbell)
    "FAB6EB2F": (7, 26),  # Preacher Curl (Dumbbell)
    "1E9A6B8E": (7, 28),  # Preacher Curl (Machine)
    "84A77566": (18, 11),  # Press Under
    "1B2B1E7C": (21, 38),  # Pull Up
    "2C37EC5E": (21, 0),  # Pull Up (Assisted)
    "56808FD2": (21, 0),  # Pull Up (Band)
    "729237D1": (21, 24),  # Pull Up (Weighted)
    "67280085": (21, 8),  # Pullover (Dumbbell)
    "B123DD01": (21, 8),  # Pullover (Machine)
    "542F3CD5": (24, 3),  # Push Press
    "392887AA": (22, 77),  # Push Up
    "19372ABC": (22, 40),  # Push Up (Weighted)
    "947DAC23": (22, 11),  # Push Up - Close Grip
    "FE389074": (8, 7),  # Rack Pull
    "C315DC2A": (9, 6),  # Rear Delt Reverse Fly (Cable)
    "E5988A0A": (9, 5),  # Rear Delt Reverse Fly (Dumbbell)
    "D8281C62": (9, 5),  # Rear Delt Reverse Fly (Machine)
    "1ADF8723": (11, 30),  # Rear Kick (Machine)
    "1B89CA1B": (23, 15),  # Renegade Row (Dumbbell)
    "7952B5CD": (6, 46),  # Reverse Crunch
    "112FC6B7": (7, 31),  # Reverse Curl (Barbell)
    "9F48F858": (7, 31),  # Reverse Curl (Cable)
    "B567DD46": (7, 31),  # Reverse Curl (Dumbbell)
    "9264ADA1": (9, 6),  # Reverse Fly Single Arm (Cable)
    "1FF4097B": (7, 31),  # Reverse Grip Concentration Curl
    "046E25A2": (21, 18),  # Reverse Grip Lat Pulldown (Cable)
    "7C0028C3": (13, 4),  # Reverse Hyperextension
    "C284D923": (17, 32),  # Reverse Lunge
    "818BA121": (17, 11),  # Reverse Lunge (Barbell)
    "FFDA283B": (17, 21),  # Reverse Lunge (Dumbbell)
    "99B49684": (19, 43),  # Reverse Plank
    "51A0EDAA": (14, 17),  # Ring Dips
    "5F09F0FC": (21, 38),  # Ring Pull Up
    "AEA56BDC": (22, 75),  # Ring Push Up
    "2B4B7310": (8, 1),  # Romanian Deadlift (Barbell)
    "72CFFAD5": (8, 4),  # Romanian Deadlift (Dumbbell)
    "234897AB": (7, 8),  # Rope Cable Curl
    "9273BA17": (21, 20),  # Rope Straight Arm Pulldown
    "0222DB42": (42, 0),  # Rowing Machine
    "AC1BB830": (32, 0),  # Running
    "BB83BDDE": (5, 46),  # Russian Twist (Bodyweight)
    "2982AA23": (5, 46),  # Russian Twist (Weighted)
    "C7AE420A": (21, 38),  # Scapular Pull Ups
    "F1D60854": (23, 18),  # Seated Cable Row - Bar Grip
    "C3BCABB3": (23, 33),  # Seated Cable Row - Bar Wide Grip
    "0393F233": (23, 32),  # Seated Cable Row - V Grip (Cable)
    "062AB91A": (1, 6),  # Seated Calf Raise
    "6B4C797E": (9, 0),  # Seated Chest Flys (Cable)
    "5122E7D9": (30, 2),  # Seated Dip Machine
    "8BAB2735": (7, 22),  # Seated Incline Curl (Dumbbell)
    "9372FFAA": (14, 24),  # Seated Lateral Raise (Dumbbell)
    "11A123F3": (15, 0),  # Seated Leg Curl (Machine)
    "91AF29E0": (24, 16),  # Seated Overhead Press (Barbell)
    "9930DF71": (24, 17),  # Seated Overhead Press (Dumbbell)
    "1006DF48": (7, 5),  # Seated Palms Up Wrist Curl
    "1DF4A847": (23, 18),  # Seated Row (Machine)
    "9237BAD1": (24, 20),  # Seated Shoulder Press (Machine)
    "234BC743": (30, 20),  # Seated Triceps Press
    "9202CC23": (7, 4),  # Seated Wrist Extension (Barbell)
    "878CD1D0": (24, 15),  # Shoulder Press (Dumbbell)
    "059E835D": (24, 20),  # Shoulder Press (Machine Plates)
    "502FCE31": (25, 3),  # Shoulder Taps
    "0B841777": (26, 1),  # Shrug (Barbell)
    "FFABC123": (26, 5),  # Shrug (Cable)
    "ABEC557F": (26, 5),  # Shrug (Dumbbell)
    "19A38071": (26, 5),  # Shrug (Machine)
    "742E5BD5": (26, 1),  # Shrug (Smith Machine)
    "37F9EDA7": (5, 8),  # Side Bend
    "026FD047": (5, 9),  # Side Bend (Dumbbell)
    "E3EDA509": (19, 66),  # Side Plank
    "8372BBCC": (9, 0),  # Single Arm Cable Crossover
    "D0C4A899": (23, 20),  # Single Arm Cable Row
    "B33B526E": (7, 7),  # Single Arm Curl (Cable)
    "1837BA23": (24, 18),  # Single Arm Landmine Press (Barbell)
    "2EE45F81": (21, 13),  # Single Arm Lat Pulldown
    "DE68C825": (14, 14),  # Single Arm Lateral Raise (Cable)
    "8347DFD1": (30, 24),  # Single Arm Tricep Extension (Dumbbell)
    "552AB030": (30, 39),  # Single Arm Triceps Pushdown (Cable)
    "629AE73D": (6, 33),  # Single Leg Extensions
    "CBC0D834": (10, 30),  # Single Leg Glute Bridge
    "487B3755": (10, 30),  # Single Leg Hip Thrust
    "D1CD146F": (10, 30),  # Single Leg Hip Thrust (Dumbbell)
    "3FD83744": (28, 0),  # Single Leg Press (Machine)
    "93472AC1": (8, 10),  # Single Leg Romanian Deadlift (Barbell)
    "937292AB": (8, 14),  # Single Leg Romanian Deadlift (Dumbbell)
    "238BA231": (1, 15),  # Single Leg Standing Calf Raise
    "E51CCBE5": (1, 15),  # Single Leg Standing Calf Raise (Barbell)
    "5DA40761": (1, 16),  # Single Leg Standing Calf Raise (Dumbbell)
    "B05C2C29": (1, 15),  # Single Leg Standing Calf Raise (Machine)
    "F5DEF1EB": (28, 62),  # Sissy Squat (Weighted)
    "022DF610": (27, 37),  # Sit Up
    "9237BA12": (27, 34),  # Sit Up (Weighted)
    "24A809EF": (2, 0),  # Skating
    "84325755": (2, 0),  # Skiing
    "875F585F": (30, 13),  # Skullcrusher (Barbell)
    "68F8A292": (30, 7),  # Skullcrusher (Dumbbell)
    "7757171F": (20, 29),  # Sled Push
    "FB09C938": (18, 9),  # Snatch
    "911A58D3": (2, 0),  # Snowboarding
    "2348AB72": (7, 3),  # Spider Curl (Barbell)
    "90427D4A": (7, 37),  # Spider Curl (Dumbbell)
    "C10A5AC9": (19, 90),  # Spiderman
    "213AB238": (41, 3),  # Spinning
    "E764B907": (18, 10),  # Split Jerk
    "20C1A3CB": (17, 28),  # Split Squat (Dumbbell)
    "9283BABA": (32, 3),  # Sprints
    "F1258206": (28, 61),  # Squat (Band)
    "D04AC939": (28, 6),  # Squat (Barbell)
    "9694DA61": (28, 61),  # Squat (Bodyweight)
    "DCFF3E9F": (28, 29),  # Squat (Dumbbell)
    "CC35A01F": (28, 61),  # Squat (Machine)
    "DDCC3821": (28, 6),  # Squat (Smith Machine)
    "B82D6418": (28, 61),  # Squat (Suspension)
    "A8814C06": (23, 18),  # Squat Row
    "4377A52B": (47, 0),  # Stair Machine (Floors)
    "4377A52C": (47, 0),  # Stair Machine (Steps)
    "ACB2751D": (11, 30),  # Standing Cable Glute Kickbacks
    "06745E58": (1, 18),  # Standing Calf Raise
    "E53CCBE5": (1, 17),  # Standing Calf Raise (Barbell)
    "6DA40660": (1, 20),  # Standing Calf Raise (Dumbbell)
    "E05C2C38": (1, 18),  # Standing Calf Raise (Machine)
    "AA52E8D2": (1, 17),  # Standing Calf Raise (Smith)
    "6120CAAB": (15, 0),  # Standing Leg Curls
    "073032BB": (24, 14),  # Standing Military Press (Barbell)
    "128A2381": (28, 66),  # Step Up
    "EE2938D1": (21, 38),  # Sternum Pull up (Gironda)
    "D2387AB1": (21, 20),  # Straight Arm Lat Pulldown (Cable)
    "2A48E443": (8, 1),  # Straight Leg Deadlift
    "527DA061": (31, 0),  # Stretching
    "D20D7BBE": (8, 15),  # Sumo Deadlift
    "3F5F8D40": (28, 69),  # Sumo Squat
    "6622E5A0": (28, 69),  # Sumo Squat (Barbell)
    "05293BCA": (28, 69),  # Sumo Squat (Dumbbell)
    "5E10D0E6": (28, 69),  # Sumo Squat (Kettlebell)
    "218DA87C": (13, 29),  # Superman
    "B60A678F": (2, 0),  # Swimming
    "08A2974E": (23, 28),  # T Bar Row
    "90E506D5": (28, 79),  # Thruster (Barbell)
    "10313AFD": (28, 79),  # Thruster (Kettlebell)
    "75BAC5C3": (27, 37),  # Toe Touch
    "B94E35E1": (6, 81),  # Toes to Bar
    "FBB62888": (4, 2),  # Torso Rotation
    "243710DE": (52, 1),  # Treadmill
    "28BB4A95": (30, 2),  # Triceps Dip
    "4B4BF8C2": (30, 2),  # Triceps Dip (Assisted)
    "10347BAC": (30, 40),  # Triceps Dip (Weighted)
    "2F8D3067": (30, 8),  # Triceps Extension (Barbell)
    "21310F5F": (30, 5),  # Triceps Extension (Cable)
    "3765684D": (30, 15),  # Triceps Extension (Dumbbell)
    "3092FADD": (30, 5),  # Triceps Extension (Machine)
    "6182EE83": (30, 5),  # Triceps Extension (Suspension)
    "EC3B69A3": (30, 3),  # Triceps Kickback (Cable)
    "6127A3AD": (30, 6),  # Triceps Kickback (Dumbbell)
    "CDC472B1": (30, 39),  # Triceps Pressdown
    "93A552C6": (30, 39),  # Triceps Pushdown
    "94B7239B": (30, 19),  # Triceps Rope Pushdown
    "7AB9A362": (26, 2),  # Upright Row (Barbell)
    "286C1D0B": (26, 6),  # Upright Row (Cable)
    "797F0782": (26, 6),  # Upright Row (Dumbbell)
    "6BE68B62": (27, 31),  # V Up
    "72880C57": (21, 13),  # Vertical Traction (Machine)
    "72297E8C": (7, 37),  # Waiter Curl (Dumbbell)
    "33EDD7DB": (32, 1),  # Walking
    "32HKJ34K": (17, 78),  # Walking Lunge
    "A733CC5B": (17, 77),  # Walking Lunge (Dumbbell)
    "A1F47ACC": (28, 83),  # Wall Ball
    "C8706C80": (28, 20),  # Wall Sit
    "79EF4E4F": (31, 0),  # Warm Up
    "7C50F118": (21, 26),  # Wide Pull Up
    "B31EB524": (30, 15),  # Wide-Elbow Triceps Press (Dumbbell)
    "0E4523F4": (7, 18),  # Wrist Roller
    "8C9D2928": (36, 0),  # Yoga
    "40C6A9FC": (28, 86),  # Zercher Squat
    "123EE239": (7, 42),  # Zottman Curl (Dumbbell)
}
